# ReflexiveRL Core Types
# Defined by Mohit Ranjan, 2026.
#
# This file establishes the fundamental abstractions for the Reflexive Reinforcement Learning 
# framework. It moves beyond standard MARL by explicitly modeling the feedback loop 
# between predictive signals and environmental transitions.

module CoreTypes

export AbstractReflexiveEnv, AbstractReflexiveAgent, ReflexiveState, PredictiveSignal
export reset!, step!, reward

"""
    ReflexiveState
A research-grade state representation that can include both raw environmental 
observations and the internal predictive state of the system.
"""
struct ReflexiveState
    raw_obs::Vector{Float32}
    prediction::Union{Nothing, Vector{Float32}}
end

"""
    PredictiveSignal
A wrapper for signals generated by the Reflexive Oracle (rho).
"""
struct PredictiveSignal
    value::Vector{Float32}
    source::String
end

"""
    AbstractReflexiveEnv
Base type for environments where the transition transition function P(s' | s, a) 
is endogenously modified by the predictive signal rho(s).
"""
abstract type AbstractReflexiveEnv end

# Interface functions for all environments
function reset! end
function step! end
function reward end

"""
    AbstractReflexiveAgent
Base type for agents capable of conditioning policies on predictive signals 
while simultaneously providing gradients for oracle refinement.
"""
abstract type AbstractReflexiveAgent end

# Placeholder for future operator definitions
# (ReflexiveBellman, FixedPointLoss, etc.)

end # module
