# LaTeX Table Generator + Research Metrics
# Based on Manuscript Section 10 (Evaluation Metrics)
# Author: Mohit Ranjan, 2026.
#
# This script:
# 1. Reads all exhaustive campaign CSVs
# 2. Computes research-specific metrics (E_stab, prediction variance as I_pred proxy)
# 3. Generates publication-ready LaTeX tables for the paper
# 4. Saves them to experiments/results/latex/

using CSV, DataFrames, Statistics, Printf

mkpath("experiments/results/latex")

# =========================================================
# HELPER: Format a Float64 as "X.XX ± XX.XX" for LaTeX tables
# =========================================================
fmt(v::Float64, s::Float64=NaN) = isnan(s) ? @sprintf("%.2f", v) : @sprintf("%.2f \\pm %.2f", v, s)
bold(v::String) = "\\textbf{$v}"

# =========================================================
# 1. TIER 1 — All-Algorithm Alpha Sweep Table
# =========================================================

println("=== Generating Tier 1 LaTeX Table ===")

t1 = CSV.read("experiments/results/processed/tier1_all_algo_full.csv", DataFrame)

# Compute E_stab as a proxy using stab_error column (already computed as |st+1 - st| mean)
t1_summary = combine(groupby(t1, [:algo, :alpha]),
    :avg_reward => mean => :reward_mean,
    :avg_reward => std  => :reward_std,
    :stab_error => mean => :estab_mean
)

# Pivot to: rows=algo, cols=alpha values
algos_t1  = sort(unique(t1_summary.algo))   
alphas_t1 = sort(unique(t1_summary.alpha))

open("experiments/results/latex/table_tier1.tex", "w") do f
    println(f, "% Tier 1: All-Algorithm Comparison across Alpha Values")
    println(f, "% Generated by generate_latex_tables.jl")
    println(f, "\\begin{table}[h]")
    println(f, "\\centering")
    println(f, "\\caption{Tier 1: Controlled Reflexive Dynamics — Average Reward under Reflexive Gain \$\\alpha\$}")
    println(f, "\\label{tab:tier1-allalgo}")
    println(f, "\\begin{tabular}{l ccc ccc}")
    println(f, "\\toprule")
    print(f,   "Algorithm")
    for a in alphas_t1; print(f, " & \$\\alpha=$(a)\$"); end
    for a in alphas_t1; print(f, " & \$E_{\\text{stab}}\$ (\$\\alpha=$(a)\$)"); end
    println(f, " \\\\")
    println(f, "\\midrule")
    
    for algo in algos_t1
        algo_data = filter(r -> r.algo == algo, t1_summary)
        print(f, algo)
        # Reward for each alpha
        for a in alphas_t1
            row = filter(r -> r.alpha ≈ a, algo_data)
            if isempty(row)
                print(f, " & --")
            else
                v = round(row[1, :reward_mean], digits=1)
                s = round(row[1, :reward_std],  digits=1)
                val_str = fmt(v, s)
                # Bold the best (highest reward) in each column
                print(f, " & $val_str")
            end
        end
        # E_stab for each alpha
        for a in alphas_t1
            row = filter(r -> r.alpha ≈ a, algo_data)
            if isempty(row)
                print(f, " & --")
            else
                v = round(row[1, :estab_mean], digits=3)
                print(f, " & $(@sprintf("%.3f", v))")
            end
        end
        println(f, " \\\\")
    end
    
    println(f, "\\bottomrule")
    println(f, "\\end{tabular}")
    println(f, "\\end{table}")
end
println("  → Saved table_tier1.tex")

# =========================================================
# 2. TIER 2 — Resource Allocation Comparison Table
# =========================================================

println("=== Generating Tier 2 LaTeX Table ===")

t2 = CSV.read("experiments/results/processed/tier2_all_algo_full.csv", DataFrame)

t2_summary = combine(groupby(t2, [:algo, :n_agents]),
    :avg_reward     => mean => :reward_mean,
    :avg_reward     => std  => :reward_std,
    :collapse_count => sum  => :total_collapses,
    :final_resource => mean => :resource_mean
)

algos_t2  = sort(unique(t2_summary.algo))
nagents   = sort(unique(t2_summary.n_agents))

open("experiments/results/latex/table_tier2.tex", "w") do f
    println(f, "% Tier 2: Multi-Agent Resource Allocation — All Algorithms")
    println(f, "% Generated by generate_latex_tables.jl")
    println(f, "\\begin{table}[h]")
    println(f, "\\centering")
    println(f, "\\caption{Tier 2: Multi-Agent Resource Allocation. Collapses = total resource depletion events across all seeds.}")
    println(f, "\\label{tab:tier2-allalgo}")
    println(f, "\\begin{tabular}{l rrr rrr rrr}")
    println(f, "\\toprule")
    println(f, "& \\multicolumn{3}{c}{\$N=3\$} & \\multicolumn{3}{c}{\$N=5\$} & \\multicolumn{3}{c}{\$N=10\$} \\\\")
    println(f, "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}")
    println(f, "Algorithm & Reward & Collapses & Resource & Reward & Collapses & Resource & Reward & Collapses & Resource \\\\")
    println(f, "\\midrule")
    
    for algo in algos_t2
        print(f, algo)
        for n in nagents
            row = filter(r -> r.algo == algo && r.n_agents == n, t2_summary)
            if isempty(row)
                print(f, " & -- & -- & --")
            else
                r_mean = round(row[1, :reward_mean], digits=1)
                colls  = row[1, :total_collapses]
                res    = round(row[1, :resource_mean], digits=3)
                print(f, " & $(@sprintf("%.1f", r_mean)) & $colls & $(@sprintf("%.3f", res))")
            end
        end
        println(f, " \\\\")
    end
    
    println(f, "\\bottomrule")
    println(f, "\\end{tabular}")
    println(f, "\\end{table}")
end
println("  → Saved table_tier2.tex")

# =========================================================
# 3. TIER 3 — Noise Bifurcation Table
# =========================================================

println("=== Generating Tier 3 LaTeX Table ===")

t3 = CSV.read("experiments/results/processed/tier3_all_algo_full.csv", DataFrame)

t3_summary = combine(groupby(t3, [:algo, :sigma_obs]),
    :avg_reward => mean => :reward_mean,
    :avg_reward => std  => :reward_std,
    :stab_error => mean => :estab_mean
)

algos_t3  = sort(unique(t3_summary.algo))
sigmas    = sort(unique(t3_summary.sigma_obs))

open("experiments/results/latex/table_tier3.tex", "w") do f
    println(f, "% Tier 3: Stochastic Partial Observability — Noise Bifurcation")
    println(f, "% Generated by generate_latex_tables.jl")
    println(f, "\\begin{table}[h]")
    println(f, "\\centering")
    println(f, "\\caption{Tier 3: Stochastic Partial Observability. Reward under increasing observation noise \$\\sigma_{obs}\$.}")
    println(f, "\\label{tab:tier3-allalgo}")
    println(f, "\\begin{tabular}{l $(repeat("r", length(sigmas)))}")
    println(f, "\\toprule")
    print(f, "Algorithm")
    for s in sigmas; print(f, " & \$\\sigma={$s}\$"); end
    println(f, " \\\\")
    println(f, "\\midrule")
    
    for algo in algos_t3
        print(f, algo)
        for s in sigmas
            row = filter(r -> r.algo == algo && r.sigma_obs ≈ s, t3_summary)
            if isempty(row)
                print(f, " & --")
            else
                v = round(row[1, :reward_mean], digits=0)
                e = round(row[1, :estab_mean],  digits=3)
                print(f, " & $(@sprintf("%.0f", v)) (\$E_{s}=\$$(@sprintf("%.3f", e)))")
            end
        end
        println(f, " \\\\")
    end
    
    println(f, "\\bottomrule")
    println(f, "\\end{tabular}")
    println(f, "\\end{table}")
end
println("  → Saved table_tier3.tex")

# =========================================================
# 4. COMPREHENSIVE METRICS TABLE (Section 10)
# Compute I_pred proxy: variance of rewards across seeds
# (high variance → oracle signals heavily influence outcomes)
# =========================================================

println("=== Generating Section 10 Metrics Table ===")

# Combine all data
all_tiers = DataFrame(
    tier  = vcat(fill("Tier1", nrow(t1)), fill("Tier2", nrow(t2)), fill("Tier3", nrow(t3))),
    algo  = vcat(t1.algo, t2.algo, t3.algo),
    reward = vcat(t1.avg_reward, t2.avg_reward, t3.avg_reward)
)

metrics_summary = combine(groupby(all_tiers, [:tier, :algo]),
    :reward => mean => :reward_mean,
    :reward => std  => :I_pred_proxy,   # High std → high prediction influence
    :reward => (x -> mean(filter(isfinite, x) .- mean(filter(isfinite, x))) / (std(filter(isfinite, x)) + 1e-8)) => :normalized_var
)

open("experiments/results/latex/table_metrics.tex", "w") do f
    println(f, "% Section 10: Research Metrics Summary")
    println(f, "% E_stab: from stab_error column in per-tier CSVs")
    println(f, "% I_pred proxy: reward std dev across seeds (high std = high prediction influence)")
    println(f, "\\begin{table}[h]")
    println(f, "\\centering")
    println(f, "\\caption{Research-specific metrics across all tiers. \$I_{\\text{pred}}\$ is approximated by cross-seed reward variance (see Section 10.3).}")
    println(f, "\\label{tab:metrics}")
    println(f, "\\begin{tabular}{ll rr}")
    println(f, "\\toprule")
    println(f, "Tier & Algorithm & Mean Reward & \$I_{\\text{pred}}\$ (Var) \\\\")
    println(f, "\\midrule")
    
    prev_tier = ""
    for row in eachrow(metrics_summary)
        if row.tier != prev_tier && prev_tier != ""
            println(f, "\\midrule")
        end
        prev_tier = row.tier
        println(f, "$(row.tier) & $(row.algo) & $(@sprintf("%.1f", row.reward_mean)) & $(@sprintf("%.1f", row.I_pred_proxy)) \\\\")
    end
    
    println(f, "\\bottomrule")
    println(f, "\\end{tabular}")
    println(f, "\\end{table}")
end
println("  → Saved table_metrics.tex")

# =========================================================
# 5. Print E_stab summary (Section 10.2, Eq. 57)
# =========================================================

println("\n=== E_stab Summary (Reflexive Stability Error, Eq. 57) ===")
println("Tier 1:")
t1_estab = combine(groupby(t1, :algo), :stab_error => mean => :estab)
println(t1_estab)

println("Tier 3 (noise-dependent):")
t3_estab = combine(groupby(t3, [:algo, :sigma_obs]), :stab_error => mean => :estab)
println(filter(r -> r.sigma_obs in [0.01, 0.5, 1.0], t3_estab))

println("\nAll LaTeX tables saved to experiments/results/latex/")
println("Files: table_tier1.tex, table_tier2.tex, table_tier3.tex, table_metrics.tex")
